name: readrift
description: "Break into your own reading universe."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  image_picker: ^1.1.2
  go_router: ^15.1.1
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/1984.png
    - assets/atomic_habits.png
    - assets/harry_potter.png
    - assets/hooked.png
    - assets/rich_dad.png
    - assets/subtle_art.png
    - assets/the_alchemist.png
    - assets/welcome_illustration.png

  fonts:
    - family: SFProRounded
      fonts:
        - asset: fonts/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Rounded-Heavy.otf
          weight: 900
    - family: FuturaPT
      fonts:
        - asset: fonts/futura-pt-extrabold.otf
          weight: 800
        - asset: fonts/Futura-Medium.otf
          weight: 500